name: cargo-pclhd
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - psutil
  - faiss-gpu
